repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        exclude: |
            (?x)(
              ^kyt-cli/openapi/|
              ^kyt-api-server/go/model.*.go
              ^kyt-api-server/go/routers.*.go
            )
      - id: end-of-file-fixer
        exclude: |
            (?x)(
              ^kyt-cli/openapi/|
              ^kyt-api-server/go/model.*.go
              ^kyt-api-server/go/routers.*.go
            )
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args: [--max-line-length=130]
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-fmt
        exclude: |
            (?x)(
              ^kyt-cli/openapi/|
              ^kyt-api-server/go/model.*.go
              ^kyt-api-server/go/routers.go
            )
      - id: go-lint
      - id: go-imports
        exclude: |
            (?x)(
              ^kyt-cli/openapi/|
              ^kyt-api-server/go/model.*.go
              ^kyt-api-server/go/routers.*.go
            )
      - id: go-mod-tidy
        exclude: |
            (?x)(
              ^kyt-cli/openapi/|
              ^kyt-api-server/go/model.*.go
              ^kyt-api-server/go/routers.*.go
            )
