parameters:
  excl: &excl |
            (?x)(
              ^kyt-cli/openapi/|
              ^kyt-api-server/api/|
              ^kyt-api-server/.openapi-generator/|
              ^kyt-api-server/go/model.*.go|
              ^kyt-api-server/go/routers.*go|
              ^kyt-api-server/go/README.md
            )
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        exclude: *excl
      - id: end-of-file-fixer
        exclude: *excl
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args: [--max-line-length=130]
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-fmt
        exclude: *excl
      - id: go-lint
      - id: go-imports
        exclude: *excl
      - id: go-mod-tidy
        exclude: *excl
