# ===================================================
# meta infos
# ===================================================
meta:
  project: kyt-cli
  include:
    - version.yaml
    - docker/dobi.yaml
    - kyt-cli/dobi.yaml
    - kyt-api-server/dobi.yaml
    - kyt-api-client/dobi.yaml

# ===================================================
# alias
# ===================================================

alias=build:
  tasks:
    - build-kyt-cli
    - build-kyt-api-server
  annotations:
    description: "[alias] build all"
    tags:
      - alias
