# ===================================================
# meta infos
# ===================================================
meta:
  project: kyt
  include:
    - dobi.yaml
    - version.yaml
    - azure-runtime/dobi.yaml
    - kubectl-runtime/dobi.yaml
    - kyt-api-spec/dobi.yaml
    - kyt-cli/dobi.yaml
    - kyt-dlm-server/dobi.yaml
    - kyt-service-deployment/dobi.yaml
    - kyt-dlm-devinfo-static/dobi.yaml
    - device-state-service/dobi.yaml
    - kyt-alm-server/dobi.yaml

# ===================================================
# alias
# ===================================================

alias=build:
  tasks:
    - build-kyt-cli
    - build-kyt-dlm-server
    - image-kyt-dlm-server
    - build-device-state-service
    - build-kyt-dlm-devinfo-static
    - build-kyt-alm-server
    - image-kyt-alm-server
  annotations:
    description: "[alias] build all"
    tags:
      - alias

alias=deploy:
  tasks:
    - image-kyt-dlm-server:push
    - image-kyt-alm-server:push
  annotations:
    description: "[alias] push all"
    tags:
      - alias

alias=aks-deploy:
  tasks:
    - deploy-cert-manager
    - deploy-ingress-nginx
    - deploy-docker-registry-secret
    - deploy-kyt-dlm-server
    - deploy-kyt-alm-server
  annotations:
    description: "[alias] deploy all"
    tags:
      - alias
