resources:
  # Upstream docker images
  - name: image-bb-gitversion-tool
    type: docker-image
    source:
      repository: elbb/bb-gitversion
      tag: 0.7.0

  - name: image-golang
    type: docker-image
    source:
      repository: golang
      tag: 1.15.6-buster

  - name: image-openapi-generator
    type: docker-image
    source:
      repository: openapitools/openapi-generator-cli
      tag: v5.0.0

  # Own docker images
  - name: image-kyt-dlm-server
    type: docker-image
    source:
      repository: harbor.ci4rail.com/ci4rail/kyt/kyt-dlm-server
      username: ((registry_user))
      password: ((registry_password))

  # Git sources
  - name: source
    type: git
    source:
      uri: ((git_source))
      branch: ((git_branch))
      skip_ssl_verification: ((git_skip_ssl_verification))

  # Github release
  - name: gh-release
    type: github-release
    source:
      owner: ci4rail
      repository: kyt
      access_token: ((github_access_token))
      release: false
      pre_release: true

jobs:
  - name: build-((name))
    public: true
    plan:
      - in_parallel:
          - get: image-bb-gitversion-tool
          - get: source
            trigger: true
          - get: image-openapi-generator
          - get: image-golang
      - in_parallel:
          - task: generate-version
            image: image-bb-gitversion-tool
            config:
              platform: linux
              inputs:
                - name: source
              outputs:
                - name: gitversion
              run:
                path: /bin/bash
                args:
                  - -exc
                  - |
                    entrypoint.sh &&
                    jq empty gitversion/json/gitversion.json &&
                    cat gitversion/json/gitversion.json
              params:
                GIT_PATH: source
                GEN_PATH: gitversion

          - task: build-generate-kyt-cli-openapi
            image: image-openapi-generator
            config:
              platform: linux
              inputs:
                - name: source
              outputs:
                - name: openapi
              run:
                path: /bin/bash
                args:
                  - -ec
                  - |
                    ROOT=$(pwd)
                    java -Xmx1024M -DloggerPath=conf/log4j.properties -jar \
                    /opt/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar \
                    generate -i source/kyt-api-spec/kytdlmapi.yaml -g go -o openapi/openapidlm --package-name openapidlm
                    rm -f openapi/openapidlm/go.mod openapi/openapidlm/go.sum

      - in_parallel:
          - task: build-kyt-cli
            image: image-golang
            config:
              platform: linux
              inputs:
                - name: source
                - name: openapi
                - name: gitversion
              outputs:
                - name: install
              run:
                path: /bin/bash
                args:
                  - -ec
                  - |
                    ROOT=$(pwd)
                    cp -r openapi/openapidlm ${ROOT}/source/kyt-cli
                    cd ${ROOT}/source/kyt-cli
                    VERSION=$(cat ${ROOT}/gitversion/plain/InformationalVersion) make
                    # copy the artifacts as a
                    cp ../bin/kyt ../bin/kyt.exe ${ROOT}/install
          - task: generate-build-args-for-image-kyt-dlm-server
            image: image-golang
            config:
              platform: linux
              inputs:
                - name: gitversion
              outputs:
                - name: kyt-dlm-server-build-args
              run:
                path: /bin/bash
                args:
                  - -ec
                  - |
                    ROOT=$(pwd)
                    echo {\"VERSION\":\"$(cat gitversion/plain/InformationalVersion)\"} > kyt-dlm-server-build-args/build-args

      - put: image-kyt-dlm-server
        params:
          build: source/
          dockerfile: source/kyt-dlm-server/Dockerfile
          latest: false
          tag_file: gitversion/plain/InformationalVersion
          build_args_file: kyt-dlm-server-build-args/build-args

      - put: gh-release
        params:
          name: gitversion/plain/InformationalVersion
          tag: gitversion/plain/InformationalVersion
          globs:
            - install/*
