resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: pull-request
    type: pull-request
    check_every: 30s
    webhook_token: ((webhook_token))
    source:
      repository: ci4rail/kyt
      access_token: ((access_token))

  - name: image-golang
    type: docker-image
    source:
      repository: golang
      tag: 1.16-buster

  - name: image-openapi-generator
    type: docker-image
    source:
      repository: openapitools/openapi-generator-cli
      tag: v5.0.0

jobs:
  - name: build
    plan:
      - in_parallel:
          - get: image-golang
          - get: image-openapi-generator

      - get: pull-request
        trigger: true
        version: every

      - put: pull-request
        params:
          path: pull-request
          status: pending

      - in_parallel:
          - task: build-generate-kyt-cli-openapi
            image: image-openapi-generator
            config:
              platform: linux
              inputs:
                - name: pull-request
              outputs:
                - name: openapi
              run:
                path: /bin/bash
                args:
                  - -ec
                  - |
                    java -Xmx1024M -DloggerPath=conf/log4j.properties -jar \
                    /opt/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar \
                    generate -i pull-request/kyt-api-spec/kytdlmapi.yaml -g go -o openapi/openapidlm --package-name openapidlm
                    rm -f openapi/openapidlm/go.mod openapi/openapidlm/go.sum
                    java -Xmx1024M -DloggerPath=conf/log4j.properties -jar \
                    /opt/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar \
                    generate -i pull-request/kyt-api-spec/kytalmapi.yaml -g go -o openapi/openapialm --package-name openapialm
                    rm -f openapi/openapialm/go.mod openapi/openapialm/go.sum
            on_failure:
              put: pull-request
              params:
                path: pull-request
                status: failure

      - in_parallel:
          - task: test-kyt-server-common
            image: image-golang
            config:
              platform: linux
              inputs:
                - name: pull-request
              run:
                path: /bin/bash
                args:
                  - -ec
                  - |
                    ROOT=$(pwd)
                    cd ${ROOT}/pull-request/kyt-server-common
                    make test
            on_failure:
              put: pull-request
              params:
                path: pull-request
                status: failure
          - task: build-kyt-cli
            image: image-golang
            config:
              platform: linux
              inputs:
                - name: pull-request
                - name: openapi
              outputs:
                - name: install
              run:
                path: /bin/bash
                args:
                  - -ec
                  - |
                    ROOT=$(pwd)
                    cp -r openapi/openapidlm ${ROOT}/pull-request/kyt-cli/
                    cp -r openapi/openapialm ${ROOT}/pull-request/kyt-cli/
                    cd ${ROOT}/pull-request/kyt-cli
                    make test
                    make
            on_failure:
              put: pull-request
              params:
                path: pull-request
                status: failure

          - task: build-kyt-dlm-server
            image: image-golang
            config:
              platform: linux
              inputs:
                - name: pull-request
              run:
                path: /bin/bash
                args:
                  - -ec
                  - |
                    ROOT=$(pwd)
                    cd ${ROOT}/pull-request/kyt-dlm-server
                    make test
                    make
            on_failure:
              put: pull-request
              params:
                path: pull-request
                status: failure

          - task: build-kyt-alm-server
            image: image-golang
            config:
              platform: linux
              inputs:
                - name: pull-request
              run:
                path: /bin/bash
                args:
                  - -ec
                  - |
                    ROOT=$(pwd)
                    cd ${ROOT}/pull-request/kyt-alm-server
                    make test
                    make
            on_failure:
              put: pull-request
              params:
                path: pull-request
                status: failure

          - task: build-kyt-dlm-server-docker-image
            privileged: true
            config:
              platform: linux
              image_resource:
                type: registry-image
                source:
                  repository: vito/oci-build-task
              inputs:
                - name: pull-request
              outputs:
                - name: image
              run:
                path: build
              params:
                CONTEXT: pull-request/
                DOCKERFILE: pull-request/kyt-dlm-server/Dockerfile
            on_failure:
              put: pull-request
              params:
                path: pull-request
                status: failure

          - task: build-kyt-alm-server-docker-image
            privileged: true
            config:
              platform: linux
              image_resource:
                type: registry-image
                source:
                  repository: vito/oci-build-task
              inputs:
                - name: pull-request
              outputs:
                - name: image
              run:
                path: build
              params:
                CONTEXT: pull-request/
                DOCKERFILE: pull-request/kyt-alm-server/Dockerfile
            on_failure:
              put: pull-request
              params:
                path: pull-request
                status: failure

      - put: pull-request
        params:
          path: pull-request
          status: success
