/*
 * KYT API Server
 *
 * This is the KYT API Server
 *
 * API version: 0.0.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// AuthLoginPost - Login
func AuthLoginPost(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// RefreshToken - Refresh token
func RefreshToken(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
