/*
 * KYT API Server
 *
 * This is the KYT API Server
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"log"
	"net/http"

	iothubservice "github.com/ci4rail/kyt-cli/kyt-api-server/iothubservice"
	"github.com/gin-gonic/gin"
)

// GetDevices - List devices for a tenant
func GetDevices(c *gin.Context) {

	iotHubConnectionString, err := iothubservice.MapTenantToIOTHubSAS("")
	if err != nil {
		log.Fatal(err)
	}

	client, err := iothubservice.ControllerNewIOTHubServiceClient(iotHubConnectionString)

	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	deviceIDs, err := client.ListDeviceIDs()

	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	var deviceList []Device
	for _, deviceID := range *deviceIDs {
		deviceList = append(deviceList, Device{Id: deviceID})
	}

	c.JSON(http.StatusOK, deviceList)
}
