/*
 * KYT API Server
 *
 * This is the KYT API Server
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// DeviceApiService is a service that implents the logic for the DeviceApiServicer
// This service should implement the business logic for every endpoint for the DeviceApi API.
// Include any external packages or services that will be required by this service.
type DeviceApiService struct {
}

// NewDeviceApiService creates a default api service
func NewDeviceApiService() DeviceApiServicer {
	return &DeviceApiService{}
}

// GetDevices - List devices for a tenant
func (s *DeviceApiService) GetDevices(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetDevices with the required logic for this service method.
	// Add api_device_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []Device{}) or use other options such as http.Ok ...
	//return Response(200, []Device{}), nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetDevices method not implemented")
}
