/*
 * KYT API Server
 *
 * This is the KYT API Server
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetDevices - List devices for a tenant
func GetDevices(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
