/*
 * KYT API Server
 *
 * This is the KYT API Server
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// User - A KYT User
type User struct {
	ID int64 `json:"id,omitempty"`

	Username string `json:"username,omitempty"`
}
