/*
 * KYT API Server
 *
 * This is the KYT API Server
 *
 * API version: 0.0.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

// Device - A Device
type Device struct {

	Id string `json:"id"`
}
