/*
 * KYT API Server
 *
 * This is the KYT API Server
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"os"

	"github.com/ci4rail/kyt/kyt-api-server/cmd"
)

const (
	envIotHubConnectionsString = "IOTHUB_SERVICE_CONNECTION_STRING"
)

func main() {
	versionArgFound := false
	for _, v := range os.Args {
		if v == "version" || v == "help" || v == "--help" || v == "-h" {
			versionArgFound = true
		}
	}
	if !versionArgFound {
		_, ok := os.LookupEnv(envIotHubConnectionsString)

		if !ok {
			log.Fatalf("Error: environment variable %s missing", envIotHubConnectionsString)
		}
	}
	cmd.Execute()
}
