---
# Project configuration
# -----------------------------
## Defines the name for the project
name: kyt-services

# Git configuration
# -----------------
## Specify the git repository to work with
git_source: git@github.com:ci4rail/kyt-cli.git
## Specify the git branch to work with
git_branch: main
## This enables/disables ssl verification of the git resource
git_skip_ssl_verification: false

# S3 configuration
# ----------------
## Specify the S3 endpoint URI
s3_endpoint: https://minio.ci4rail.com
## This enables/disables the ssl verification for the S3 endpoint
s3_skip_ssl_verification: false
