openapi: 3.0.0
servers:
  - url: 'https://kyt.ci4rail.com/v1'
    description: Production Server
info:
  description: >-
    This is the KYT API Server
  version: 0.0.1
  title: KYT API Server
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: device
    description: A connected device
paths:
  '/dlm/devices':
    get:
      tags:
        - device
      summary: List devices for a tenant
      description: Returns a list of devices
      operationId: getDevices
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Device'
        '400':
          description: Invalid ID supplied
      security:
        - api_key: []
  '/auth/login':
    post:
      tags:
        - auth
      summary: Login
      requestBody:
        content:
          application/json:
            schema:      # Request body contents
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              example:   # Sample object
                username: user
                password: password
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  '/auth/refresh_token':
    get:
      tags:
        - auth
      summary: Refresh token
      description: Refreshs a token
      operationId: refreshToken
      responses:
        '200':
          description: successful operation
        '400':
          description: Error refreshing
      security:
        - api_key: []
components:
  requestBodies:
    Device:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Device'
        application/xml:
          schema:
            $ref: '#/components/schemas/Device'
      description: Device object
      required: true
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
  schemas:
    Device:
      title: a Device
      description: A Device
      type: object
      required:
        - id
      properties:
        id:
          type: string
      xml:
        name: Device
