openapi: 3.0.0
info:
  title: Application Lifecycle Management API
  description: Public API to manage asigned Application Runtimes.
  version: 0.0.1
  license:
    name: Apache-2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: "https://alm.ci4rail.com/v1"
    description: Production Server
tags:
  - name: alm
    description: Application Lifecycle Management
paths:
  "/runtimes/":
    get:
      tags:
        - runtimes
      summary: List runtimes for a tenant
      description: Returns a list of runtimes
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Runtime"
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      security:
        - bearerAuth: []
  "/runtimes/{rid}":
    parameters:
      - $ref: "#/components/parameters/Rid"
    get:
      tags:
        - runtimes
      responses:
        '200':
          $ref: "#/components/responses/Runtime"
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      security:
        - bearerAuth: []
  "/apply/":
    put:
      tags:
        - deployment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomerManifest"
      responses:
        '200':
          description: OK
        '403':
          description: Forbidden
        '500':
          description: Internal Error
      security:
        - bearerAuth: []
components:
  parameters:
    Rid:
      name: rid
      description: id of runtime
      in: path
      required: true
      schema:
        type: string

  responses:
    Runtime:
      description: Ok
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Runtime"

  schemas:
    Runtime:
      type: object
      required:
        - id
      properties:
        id:
          type: string
        name:
          type: string
        network:
          type: string
          enum: [offline, online]
      example:
        id: runtime234
        name: runtime1
        network: offline

    CustomerManifest:
      type: object
      required:
        - application
        - modules
      properties:
        application:
          type: string
        modules:
          type: array
          items:
            $ref: "#/components/schemas/ModuleType"

    ModuleType:
      type: object
      required:
        - name
        - image
      properties:
        name:
          type: string
        image:
          type: string
        createOptions:
          type: string
          default: "{}"
        imagePullPolicy:
          type: string
          enum:
            - on-create
            - never
          default: on-create
        restartPolicy:
          type: string
          enum:
            - always
            - never
            - on-failure
            - on-unhealthy
          default: always
        status:
          type: string
          enum:
            - running
            - stopped
          default: running
        startupOrder:
          type: integer
          minimum: 100
          maximum: 199
          default: 100

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
